---
title: '...if looks could kill (selfies actually can kill you)'
author: Martin Frigaard
date: '2019-05-08'
slug: if-looks-could-kill-selfies-actually-can-kill-you
categories:
  - On Measurement
tags:
  - epidemiology
description: 'researchers in India found selfie-related deaths have risen over the last 6 years'
topics: []
---

A 2018 paper in the Journal of Family Medicine and Primary Care looked into the rates of selfie-related deaths around the world and found some surprising results. [Selfies: A boon or bane?](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6131996/) was authored by Agam Bansal, Chandan Garg, Abhijith Pakhare, and Samiksha Gupta from Community and Family Medicine, All India Institute of Medical Sciences, Bhopal, Madhya Pradesh, India and the Department of Civil Engineering, IIT Kanpur, Kanpur, Uttar Pradesh, India.

> "*If ever a face meant death--if looks could kill--we saw it at that moment.*" - Dr. Seward, Bram Stoker's Dracula

[Selfie](https://en.wikipedia.org/wiki/Selfie)'s are "*photograph[s] that one has taken of oneself, typically one taken with a smartphone or webcam and uploaded to a social media website.*" Selfies became popular with the widespread adoption of smartphones, and almost overnight social media sites like Facebook, Twitter, and Instagram were flooded images of people's faces. 

But these aren't head shots or Glamour Shots (yes, those are [still a thing](https://www.glamourshots.com/galleries/)). Selfies have a distinct look and feel because of the almost obsessive levels of detail placed on getting just the right angle, framing and side of the face (yes, there is a right side, and it's [NOT the right side](https://www.latrobe.edu.au/news/articles/2017/release/selfies-did-you-get-your-best-side)).

Many people have criticized them, too. They've been called the [“*the masturbation of self-image*”](https://www.esquire.com/entertainment/a23557/selfies-arent-art/) and ["*virtual "mini-me," what in ancient biology might have been called a "homunculus" – a tiny pre-formed person that would grow into the big self.*"](https://www.youtube.com/watch?v=4ux0d1oQdCQ) Whatever your opinion is on selfies, the authors make a pretty strong case for paying attention to how dangerous they can be.

## What did they measure?

The authors used publicly available data to complete this analysis. From their methods section: 

> Initially, we made an exhaustive list of the English newspapers of various countries using Wikipedia or Ministry of broadcasting of respective countries. We performed a Google search for keywords such as “selfie deaths; selfie accidents; selfie mortality; self photography deaths; koolfie deaths; mobile death/accidents.”

I contacted the authors for more details on the methods they used. They responded with: 



## What did they find?

