---
title: "Integrity in publishing (Ty Cobb: A Terrible Beauty book review)"
author: Martin
date: '2018-01-18'
slug: integrity-in-publishing-ty-cobb-a-terrible-beauty-book-review
categories: [sports]
tags: []
---


I recently purchased and read [Ty Cobb: A Terrible Beauty](https://www.amazon.com/Ty-Cobb-Terrible-Charles-Leerhsen/dp/1451645791) by Charles Leerhsen after watching his lecture at [Hillsdale College](https://www.youtube.com/watch?v=OjbPzoboilM). I'd always thought of Ty Cobb as the character portrayed by Tommy Lee Jones in the 1994 [film **Cobb**](http://www.imdb.com/title/tt0109450/). Even before seeing this film, Ty Cobb's reputation for being rotten was pervasive--when referring to him in [**Field of Dreams**](https://en.wikipedia.org/wiki/Field_of_Dreams), Shoeless Joe Jackson states, "*No one liked that son of a bitch.*"

Unfortunately for Cobb (and anyone interested in the facts), those portrayals of the baseball hall-of-famer's life and character are highly fictionalized. Most of the popular opinions of Ty Cobb come from two biographies: Charles C. Alexander's [Ty Cobb](https://www.amazon.com/Ty-Cobb-Charles-C-Alexander/dp/0870745093), and Al Stump's [Cobb](https://www.amazon.com/Cobb-Biography-Al-Stump/dp/1565121449). Both authors construct a narrative that depicts Cobb as a drunk, ill-tempered bully who sharpened his cleats and screamed racial epithets at his hired help. 

Leerhsen does a fantastic job addressing how both of these stories are likely fiction, created by the authors in hopes to increase book sales. The racist baseball star makes for quite a villain and a compelling character. Painting Cobb as a monster was a guaranteed way to elicit a sense of disgust and attract attention.

From the epilogue,   

> *This Cobb was someone they could shake their head at, denounce, and feel superior to. Spinning stories in a way that made him look immoral was a convenient way to say, "I am not a racist because I reject this man who is." Cultures change as values change, wars are waged and the harvest waxes and wanes, but a villain who inspires self-congratulation makes for one hell of a tenacious myth.*

The tragedy of Ty Cobb's narrative is the insightful baseball and general life lessons the man had to offer. Leerhsen distills Cobb's philosophy on baseball into two words: **pay attention**. Cobb would spend endless hours mentally rehearsing the game, taking notes, and thinking up possible scenarios and plays. He also paid attention to the minds of his opponents. 

Another example from Leerhsen, 

> *After [Cobb] noticed how upset the good-hearted Big Train got when he beaned batters, Cobb stood in against him as he did against nobody else, hunching over the plate and sticking his head into the strike zone. He could have gotten killed; instead, very often, he got walked.*

Anyone who has read [Moneyball](https://www.amazon.com/Moneyball-Art-Winning-Unfair-Game/dp/0393324818) knows the importance of walks and on-base percentage sees the genius at work here. 

The takeaway lesson I have from this book isn't actually from the book. It was a woman who stood and gave praise during the Q&A portion of Leerhsen's [lecture](https://www.youtube.com/watch?v=OjbPzoboilM),

> "*... you've written a cautionary tale that in a complicated political season has a lesson for us...what happened to Ty Cobb could not happen today because everybody knows everything, but it does happen. So thank you for your courage in writing a book that reminds us that we don't know everything until we really know somebody and that everything that we think we know we should re-examine several times with a clear conscience and our own integrity before we make those judgments. Thank you very much...*"

The last portion of the woman's statement resonated with me. In an era of 'fake news' and 'alternative facts,' it's refreshing to hear praise for this kind of honesty. 

Wikipedia defines integrity in ethics as, "*the honesty and truthfulness or accuracy of one's actions.*" I had a coach define it as, "*doing what you know is right even when no one is looking*." I think Leerhsen's integrity involved a lot of both, and I hope this book helps set the record straight for future generations.



